osx_image: xcode8
language: objective-c

before_install:
- brew update
- if brew outdated | grep -qx carthage; then brew upgrade carthage; fi
- travis_wait 35 carthage bootstrap --platform iOS,Mac

script:
- xcodebuild clean build -project Reindeer.xcodeproj -scheme Reindeer-iOS -sdk iphonesimulator
- xcodebuild test -project Reindeer.xcodeproj -scheme Reindeer-iOS -sdk iphonesimulator
- xcodebuild clean build -project Reindeer.xcodeproj -scheme Reindeer-Mac -sdk macosx
- xcodebuild test -project Reindeer.xcodeproj -scheme Reindeer-Mac -sdk macosx
